"""Domain Architect process-machine smoke tests."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from da_machine import classify_claim, cosmos_drill, run_checker  # noqa: E402
from da_sixteen import SIXTEEN  # noqa: E402


class DaMachineTests(unittest.TestCase):
    def test_forbidden_close_fails(self):
        r = classify_claim("I solved NS and RH last May")
        self.assertEqual(r["verdict"], "fail")

    def test_theorem_p_lands_in_q(self):
        r = classify_claim("Theorem P: the prime block of Q-tilde sits above -1/4")
        self.assertEqual(r["domain"], "Q")
        self.assertEqual(r["verdict"], "open")

    def test_unassigned_stays_open(self):
        r = classify_claim("hello there")
        self.assertIsNone(r["domain"])
        self.assertEqual(r["verdict"], "open")

    def test_cosmos_drill_names_found_f_still_private(self):
        d = cosmos_drill()
        self.assertTrue(d["cosmos_list_found"])
        self.assertFalse(d["cosmos_core_equation_public"])
        self.assertEqual(d["n_confirmed"], 16)
        self.assertEqual(d["possibility_claim"]["verdict"], "open")
        self.assertEqual(len(d["layers"][0]["pieces"]), 16)
        self.assertEqual(d["layers"][2]["pieces"], ["log_cc_ratio", "log_hierarchy"])

    def test_sixteen_command_list_is_wired(self):
        self.assertEqual(len(SIXTEEN), 16)
        self.assertEqual(SIXTEEN[-1], "R")

    def test_fingers_claim_lands_in_u(self):
        r = classify_claim("five finger DA on the realization line")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_wave_claim_lands_in_u(self):
        r = classify_claim("can we use superposition and falsification on the waveform")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_sm_lagrangian_lands_in_u(self):
        r = classify_claim("analyze the Standard Model Lagrangian and the Weinberg rotation")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_dream_team_lands_in_u(self):
        r = classify_claim("bring in the dream team from beyond the digital divide")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_session_converse_lands_in_u(self):
        r = classify_claim("have the dream team converse and talk to each other")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")
        r2 = classify_claim("a virtual seance of carved-out kingdoms on one problem")
        self.assertEqual(r2["domain"], "U")
        self.assertEqual(r2["verdict"], "open")

    def test_living_dream_team_lands_in_u(self):
        r = classify_claim("seat the living dream team that is not dead")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")
        r2 = classify_claim("bring in the living bench and pretend they sit")
        self.assertEqual(r2["domain"], "U")
        self.assertEqual(r2["verdict"], "open")

    def test_full_roll_leads_land_in_u(self):
        r = classify_claim("ask every chair and all specialties for a next lead")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")
        r2 = classify_claim("full roll of the think tank for one lead each")
        self.assertEqual(r2["domain"], "U")
        self.assertEqual(r2["verdict"], "open")

    def test_harmonic_vocab_lands_in_u(self):
        r = classify_claim("can DA make a complete harmonic vocabulary out of mathematics")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_ground_destination_lands_in_u(self):
        r = classify_claim("harmonic universe as a spectrum not a bag of couplings; ask Feynman")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_pipe_think_tank_lands_in_u(self):
        r = classify_claim("pipe satellite and hologram data into the think tank")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_desk_writeup_lands_in_u(self):
        r = classify_claim("write up the whole desk and the corpus method")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_compute_techniques_land_in_u(self):
        r = classify_claim("computing techniques we can borrow: sympy and Dedalus")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_alert_lands_in_u(self):
        r = classify_claim("text me a plain language alert when something significant flips")
        self.assertEqual(r["domain"], "U")
        self.assertEqual(r["verdict"], "open")

    def test_tube_hardy_lands_in_b_and_solved_ns_fails(self):
        r = classify_claim("localized tube Hardy for Gamma, keep 1/r^4")
        self.assertEqual(r["domain"], "B")
        self.assertEqual(r["verdict"], "open")
        occ = classify_claim("occupation time of 3-CONC vs SPREAD")
        self.assertEqual(occ["domain"], "B")
        self.assertEqual(occ["verdict"], "open")
        glue = classify_claim("two-regime glue of B4c CONC to energy-class T")
        self.assertEqual(glue["domain"], "B")
        self.assertEqual(glue["verdict"], "open")
        ceil = classify_claim("energy ceiling on a frozen low-j packet")
        self.assertEqual(ceil["domain"], "B")
        self.assertEqual(ceil["verdict"], "open")
        climb = classify_claim("climbing CONC with a climb law for dj*/dt")
        self.assertEqual(climb["domain"], "B")
        self.assertEqual(climb["verdict"], "open")
        field = classify_claim("barycenter climb law from the vorticity field")
        self.assertEqual(field["domain"], "B")
        self.assertEqual(field["verdict"], "open")
        geo = classify_claim("strain eigenframe alignment on a vorticity packet")
        self.assertEqual(geo["domain"], "B")
        self.assertEqual(geo["verdict"], "open")
        stretch = classify_claim("stretching budget and weighted alignment on a vorticity packet")
        self.assertEqual(stretch["domain"], "B")
        self.assertEqual(stretch["verdict"], "open")
        bal = classify_claim("enstrophy balance production versus dissipation on a vorticity packet")
        self.assertEqual(bal["domain"], "B")
        self.assertEqual(bal["verdict"], "open")
        ang = classify_claim("angular viscosity versus I_tube on a swirl packet")
        self.assertEqual(ang["domain"], "B")
        self.assertEqual(ang["verdict"], "open")
        coh = classify_claim("signed strain blob on a coherent CONC vorticity packet")
        self.assertEqual(coh["domain"], "B")
        self.assertEqual(coh["verdict"], "open")
        focc = classify_claim("field occupation of 3-CONC along a vorticity path")
        self.assertEqual(focc["domain"], "B")
        self.assertEqual(focc["verdict"], "open")
        fgl = classify_claim("field glue of the two-regime sketch against vorticity Ẋ")
        self.assertEqual(fgl["domain"], "B")
        self.assertEqual(fgl["verdict"], "open")
        nsc = classify_claim("NS climb of j_bar on a vorticity blob")
        self.assertEqual(nsc["domain"], "B")
        self.assertEqual(nsc["verdict"], "open")
        csk = classify_claim("climb sketch of prescribed c against a vorticity window")
        self.assertEqual(csk["domain"], "B")
        self.assertEqual(csk["verdict"], "open")
        lng = classify_claim("longer path of a vorticity packet past the climb room time")
        self.assertEqual(lng["domain"], "B")
        self.assertEqual(lng["verdict"], "open")
        dns = classify_claim("packet DNS as an a priori bound for vorticity")
        self.assertEqual(dns["domain"], "B")
        self.assertEqual(dns["verdict"], "open")
        tb = classify_claim("tube budget of vorticity as an a priori")
        self.assertEqual(tb["domain"], "B")
        self.assertEqual(tb["verdict"], "open")
        aln = classify_claim("alignment as an a priori bound for vorticity")
        self.assertEqual(aln["domain"], "B")
        self.assertEqual(aln["verdict"], "open")
        pay = classify_claim("aligned stretching payers on a vorticity packet")
        self.assertEqual(pay["domain"], "B")
        self.assertEqual(pay["verdict"], "open")
        net = classify_claim("enstrophy net as an a priori bound for vorticity")
        self.assertEqual(net["domain"], "B")
        self.assertEqual(net["verdict"], "open")
        blob = classify_claim("signed blob as an a priori bound for vorticity")
        self.assertEqual(blob["domain"], "B")
        self.assertEqual(blob["verdict"], "open")
        clock = classify_claim("field clock as an a priori bound for vorticity")
        self.assertEqual(clock["domain"], "B")
        self.assertEqual(clock["verdict"], "open")
        match = classify_claim("matching the sketch as an a priori bound for vorticity")
        self.assertEqual(match["domain"], "B")
        self.assertEqual(match["verdict"], "open")
        sav = classify_claim("saving climb as an a priori bound for vorticity")
        self.assertEqual(sav["domain"], "B")
        self.assertEqual(sav["verdict"], "open")
        win = classify_claim("climb window as an a priori bound for vorticity")
        self.assertEqual(win["domain"], "B")
        self.assertEqual(win["verdict"], "open")
        finer = classify_claim("finer box as an a priori bound for vorticity")
        self.assertEqual(finer["domain"], "B")
        self.assertEqual(finer["verdict"], "open")
        mesh = classify_claim("finer DNS as an a priori bound for vorticity")
        self.assertEqual(mesh["domain"], "B")
        self.assertEqual(mesh["verdict"], "open")
        close = classify_claim("leftover close as an a priori bound for vorticity")
        self.assertEqual(close["domain"], "B")
        self.assertEqual(close["verdict"], "open")
        obj = classify_claim("regularity leftover as an a priori bound for vorticity")
        self.assertEqual(obj["domain"], "B")
        self.assertEqual(obj["verdict"], "open")
        resid = classify_claim("residual holes of synthetic R on a vorticity packet")
        self.assertEqual(resid["domain"], "B")
        self.assertEqual(resid["verdict"], "open")
        miller = classify_claim("miller cut of lambda_2 on a vorticity packet")
        self.assertEqual(miller["domain"], "B")
        self.assertEqual(miller["verdict"], "open")
        empty = classify_claim("empty rename of det plus on a vorticity packet")
        self.assertEqual(empty["domain"], "B")
        self.assertEqual(empty["verdict"], "open")
        blanks = classify_claim("A1 A2 blanks on a vorticity packet")
        self.assertEqual(blanks["domain"], "B")
        self.assertEqual(blanks["verdict"], "open")
        path = classify_claim("A2 path of lambda_2 on a vorticity packet")
        self.assertEqual(path["domain"], "B")
        self.assertEqual(path["verdict"], "open")
        walls = classify_claim("seat Miller and Albritton as walls on the living bench")
        self.assertEqual(walls["domain"], "U")
        self.assertEqual(walls["verdict"], "open")
        beirao = classify_claim("seat Beirao-Berselli as a wall on the living bench")
        self.assertEqual(beirao["domain"], "U")
        self.assertEqual(beirao["verdict"], "open")
        grujic_if = classify_claim("Grujic logarithmic bmo if on a vorticity packet")
        self.assertEqual(grujic_if["domain"], "B")
        self.assertEqual(grujic_if["verdict"], "open")
        giga = classify_claim("seat Giga-Miura as a wall on the living bench")
        self.assertEqual(giga["domain"], "U")
        self.assertEqual(giga["verdict"], "open")
        giga_if = classify_claim("Giga-Miura type I continuous direction if on a vorticity packet")
        self.assertEqual(giga_if["domain"], "B")
        self.assertEqual(giga_if["verdict"], "open")
        cfm = classify_claim("CFM Euler geometric if on a vorticity packet")
        self.assertEqual(cfm["domain"], "B")
        self.assertEqual(cfm["verdict"], "open")
        ss = classify_claim("self-similar profile exclusion on a vorticity packet")
        self.assertEqual(ss["domain"], "B")
        self.assertEqual(ss["verdict"], "open")
        anc = classify_claim("Liouville ancient remaining doors on a vorticity packet")
        self.assertEqual(anc["domain"], "B")
        self.assertEqual(anc["verdict"], "open")
        jia = classify_claim("seat Jia as a wall on the living bench")
        self.assertEqual(jia["domain"], "U")
        self.assertEqual(jia["verdict"], "open")
        jia_if = classify_claim("Jia forward self-similar large data on a vorticity packet")
        self.assertEqual(jia_if["domain"], "B")
        self.assertEqual(jia_if["verdict"], "open")
        guillod = classify_claim("seat Guillod as a wall on the living bench")
        self.assertEqual(guillod["domain"], "U")
        self.assertEqual(guillod["verdict"], "open")
        pitch = classify_claim("Guillod numerical pitchfork on a vorticity packet")
        self.assertEqual(pitch["domain"], "B")
        self.assertEqual(pitch["verdict"], "open")
        hwy = classify_claim("seat Hou-Wang-Yang as a wall on the living bench")
        self.assertEqual(hwy["domain"], "U")
        self.assertEqual(hwy["verdict"], "open")
        unforced = classify_claim("Hou-Wang-Yang unforced Leray-Hopf on a vorticity packet")
        self.assertEqual(unforced["domain"], "B")
        self.assertEqual(unforced["verdict"], "open")
        lei = classify_claim("seat Lei-Ren-Tian as a wall on the living bench")
        self.assertEqual(lei["domain"], "U")
        self.assertEqual(lei["verdict"], "open")
        cone = classify_claim("Lei-Ren-Tian double cone if on a vorticity packet")
        self.assertEqual(cone["domain"], "B")
        self.assertEqual(cone["verdict"], "open")
        csty = classify_claim("seat CSTY as a wall on the living bench")
        self.assertEqual(csty["domain"], "U")
        self.assertEqual(csty["verdict"], "open")
        axisym = classify_claim("Chen-Strain-Tsai-Yau axisymmetric Type I on a vorticity packet")
        self.assertEqual(axisym["domain"], "B")
        self.assertEqual(axisym["verdict"], "open")
        kozono = classify_claim("seat Kozono-Taniuchi as a wall on the living bench")
        self.assertEqual(kozono["domain"], "U")
        self.assertEqual(kozono["verdict"], "open")
        bmo = classify_claim("Kozono-Taniuchi BMO continuation on a vorticity packet")
        self.assertEqual(bmo["domain"], "B")
        self.assertEqual(bmo["verdict"], "open")
        neustupa = classify_claim("seat Neustupa-Penel as a wall on the living bench")
        self.assertEqual(neustupa["domain"], "U")
        self.assertEqual(neustupa["verdict"], "open")
        one = classify_claim("Neustupa-Penel one-component if on a vorticity packet")
        self.assertEqual(one["domain"], "B")
        self.assertEqual(one["verdict"], "open")
        ess = classify_claim("seat Escauriaza as a wall on the living bench")
        self.assertEqual(ess["domain"], "U")
        self.assertEqual(ess["verdict"], "open")
        l3 = classify_claim("Escauriaza L3 endpoint on a vorticity packet")
        self.assertEqual(l3["domain"], "B")
        self.assertEqual(l3["verdict"], "open")
        nadi = classify_claim("seat Nadirashvili as a wall on the living bench")
        self.assertEqual(nadi["domain"], "U")
        self.assertEqual(nadi["verdict"], "open")
        knss = classify_claim("KNSS ancient Liouville on a vorticity packet")
        self.assertEqual(knss["domain"], "B")
        self.assertEqual(knss["verdict"], "open")
        chae = classify_claim("seat Chae as a wall on the living bench")
        self.assertEqual(chae["domain"], "U")
        self.assertEqual(chae["verdict"], "open")
        tl = classify_claim("Chae Triebel-Lizorkin geometric if on a vorticity packet")
        self.assertEqual(tl["domain"], "B")
        self.assertEqual(tl["verdict"], "open")
        chemin = classify_claim("seat Chemin-Gallagher as a wall on the living bench")
        self.assertEqual(chemin["domain"], "U")
        self.assertEqual(chemin["verdict"], "open")
        besov = classify_claim("Chemin-Gallagher large Besov data on a vorticity packet")
        self.assertEqual(besov["domain"], "B")
        self.assertEqual(besov["verdict"], "open")
        cannone = classify_claim("seat Cannone-Planchon as a wall on the living bench")
        self.assertEqual(cannone["domain"], "U")
        self.assertEqual(cannone["verdict"], "open")
        mild = classify_claim("Cannone-Planchon critical Besov mild on a vorticity packet")
        self.assertEqual(mild["domain"], "B")
        self.assertEqual(mild["verdict"], "open")
        lin = classify_claim("seat Lin as a wall on the living bench")
        self.assertEqual(lin["domain"], "U")
        self.assertEqual(lin["verdict"], "open")
        ckn = classify_claim("Lin new proof of CKN on a vorticity packet")
        self.assertEqual(ckn["domain"], "B")
        self.assertEqual(ckn["verdict"], "open")
        vasseur = classify_claim("seat Vasseur as a wall on the living bench")
        self.assertEqual(vasseur["domain"], "U")
        self.assertEqual(vasseur["verdict"], "open")
        degiorgi = classify_claim("Vasseur De Giorgi proof of CKN on a vorticity packet")
        self.assertEqual(degiorgi["domain"], "B")
        self.assertEqual(degiorgi["verdict"], "open")
        farwig = classify_claim("seat Farwig as a wall on the living bench")
        self.assertEqual(farwig["domain"], "U")
        self.assertEqual(farwig["verdict"], "open")
        weak = classify_claim("Farwig very weak solutions on a vorticity packet")
        self.assertEqual(weak["domain"], "B")
        self.assertEqual(weak["verdict"], "open")
        cheskidov = classify_claim("seat Cheskidov as a wall on the living bench")
        self.assertEqual(cheskidov["domain"], "U")
        self.assertEqual(cheskidov["verdict"], "open")
        energy = classify_claim("Cheskidov energy equality on a vorticity packet")
        self.assertEqual(energy["domain"], "B")
        self.assertEqual(energy["verdict"], "open")
        masmoudi = classify_claim("seat Masmoudi as a wall on the living bench")
        self.assertEqual(masmoudi["domain"], "U")
        self.assertEqual(masmoudi["verdict"], "open")
        uniq = classify_claim("Masmoudi uniqueness of mild solutions on a vorticity packet")
        self.assertEqual(uniq["domain"], "B")
        self.assertEqual(uniq["verdict"], "open")
        wolf = classify_claim("seat Wolf as a wall on the living bench")
        self.assertEqual(wolf["domain"], "U")
        self.assertEqual(wolf["verdict"], "open")
        press = classify_claim("Wolf local pressure on a vorticity packet")
        self.assertEqual(press["domain"], "B")
        self.assertEqual(press["verdict"], "open")
        bad = classify_claim("I solved NS last May")
        self.assertEqual(bad["verdict"], "fail")

    def test_check_b_stays_open_when_lemmas_hold(self):
        result = run_checker("B")
        self.assertEqual(result["verdict"], "open")
        self.assertIn("Regularity stays open", result["reason"])


if __name__ == "__main__":
    unittest.main()
