"""Track B lemma checks. Identities may pass; regularity stays open."""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from track_b_lemmas import run  # noqa: E402


class TrackBLemmaTests(unittest.TestCase):
    def test_identities_pass_regularity_open(self):
        tmp = Path(tempfile.mkdtemp()) / "track_b_test.json"
        payload = run(out=tmp)
        self.assertEqual(payload["meta"]["domain_verdict"], "open")
        self.assertTrue(payload["meta"]["not_a_regularity_proof"])
        self.assertTrue(payload["meta"]["no_q1"])
        self.assertTrue(payload["meta"]["no_A_implies_B"])
        by = {row["name"]: row for row in payload["lemmas"]}
        self.assertEqual(by["B1_t2_low_flux"]["verdict"], "pass")
        self.assertEqual(by["B1b_t2_lemma2_dropped"]["verdict"], "fail")
        self.assertEqual(by["B2_regime_cover"]["verdict"], "pass")
        self.assertEqual(by["B3_three_shell_ring"]["verdict"], "pass")
        self.assertEqual(by["B3b_ring_is_not_depletion"]["verdict"], "fail")
        self.assertEqual(by["B4_tube_hardy"]["verdict"], "pass")
        self.assertEqual(by["B4b_hardy_not_I_tube"]["verdict"], "fail")
        self.assertEqual(by["B4c_packet_hardy_tube"]["verdict"], "pass")
        self.assertEqual(by["B4d_wall_matches_off_axis"]["verdict"], "pass")
        self.assertEqual(by["B5_swirl_visc_identity"]["verdict"], "pass")
        self.assertEqual(by["B5b_tube_vs_viscosity"]["verdict"], "fail")
        self.assertEqual(by["B5c_angular_climbs"]["verdict"], "pass")
        self.assertEqual(by["B5d_killer_not_angular_kill"]["verdict"], "fail")
        self.assertEqual(by["B5e_not_a_phi_cancel"]["verdict"], "fail")
        self.assertEqual(by["B5f_angular_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B5g_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B6_energy_not_enough"]["verdict"], "fail")
        self.assertEqual(by["B_phi_not_estimate_variable"]["verdict"], "fail")
        self.assertEqual(by["B7_bony_split"]["verdict"], "pass")
        self.assertEqual(by["B7a_self_is_t2"]["verdict"], "pass")
        self.assertEqual(by["B7b_low_T_energy_class"]["verdict"], "pass")
        self.assertEqual(by["B7c_low_T_not_rho_uniform"]["verdict"], "fail")
        self.assertEqual(by["B8_occupation_clock"]["verdict"], "pass")
        self.assertEqual(by["B8a_high_jstar_short"]["verdict"], "pass")
        self.assertEqual(by["B8b_leray_not_occupation"]["verdict"], "fail")
        self.assertEqual(by["B8c_occupation_not_X_bound"]["verdict"], "fail")
        self.assertEqual(by["B9_glue_bookkeeping"]["verdict"], "pass")
        self.assertEqual(by["B9a_glue_high_jstar"]["verdict"], "pass")
        self.assertEqual(by["B9b_glue_low_jstar_blows"]["verdict"], "fail")
        self.assertEqual(by["B9c_glue_switching"]["verdict"], "pass")
        self.assertEqual(by["B9d_glue_not_X_a_priori"]["verdict"], "fail")
        self.assertEqual(by["B10_energy_ceiling"]["verdict"], "pass")
        self.assertEqual(by["B10a_frozen_blow_not_ns"]["verdict"], "fail")
        self.assertEqual(by["B10b_ceiling_not_climbing"]["verdict"], "fail")
        self.assertEqual(by["B10c_climbing_conc_open"]["verdict"], "open")
        self.assertEqual(by["B10d_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B11_climb_bookkeeping"]["verdict"], "pass")
        self.assertEqual(by["B11a_bounded_j_bounds_X"]["verdict"], "pass")
        self.assertEqual(by["B11b_slow_climb_blows"]["verdict"], "fail")
        self.assertEqual(by["B11c_fast_climb_sits"]["verdict"], "pass")
        self.assertEqual(by["B11d_ns_climb_law"]["verdict"], "fail")
        self.assertEqual(by["B11e_climb_not_X_a_priori"]["verdict"], "fail")
        self.assertEqual(by["B12_barycenter"]["verdict"], "pass")
        self.assertEqual(by["B12a_c_from_rhs"]["verdict"], "pass")
        self.assertEqual(by["B12b_t0_not_saving"]["verdict"], "fail")
        self.assertEqual(by["B12c_visc_pulls_down"]["verdict"], "fail")
        self.assertEqual(by["B12d_evolved_cascade_open"]["verdict"], "open")
        self.assertEqual(by["B12e_law_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B13_short_run"]["verdict"], "pass")
        self.assertEqual(by["B13a_no_saving_climb"]["verdict"], "fail")
        self.assertEqual(by["B13b_no_high_fill"]["verdict"], "fail")
        self.assertEqual(by["B13c_stays_conc"]["verdict"], "pass")
        self.assertEqual(by["B13d_visc_still_down"]["verdict"], "fail")
        self.assertEqual(by["B13e_longer_not_saving"]["verdict"], "fail")
        self.assertEqual(by["B13f_evolve_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B14_strain_identity"]["verdict"], "pass")
        self.assertEqual(by["B14a_conc_not_depleted"]["verdict"], "fail")
        self.assertEqual(by["B14b_ring_not_alignment"]["verdict"], "fail")
        self.assertEqual(by["B14c_cf_conditional"]["verdict"], "pass")
        self.assertEqual(by["B14d_geometry_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B14e_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B15_stretch_budget"]["verdict"], "pass")
        self.assertEqual(by["B15a_cf_weights_budget"]["verdict"], "pass")
        self.assertEqual(by["B15b_majority_from_aligned"]["verdict"], "pass")
        self.assertEqual(by["B15c_run_not_depleted"]["verdict"], "fail")
        self.assertEqual(by["B15d_run_keeps_aligned_budget"]["verdict"], "fail")
        self.assertEqual(by["B15e_budget_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B15f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B16_enstrophy_identity"]["verdict"], "pass")
        self.assertEqual(by["B16a_visc_owns_net"]["verdict"], "pass")
        self.assertEqual(by["B16b_plus_not_net_cubic"]["verdict"], "fail")
        self.assertEqual(by["B16c_l2_is_not_bkm"]["verdict"], "fail")
        self.assertEqual(by["B16d_not_all_conc"]["verdict"], "fail")
        self.assertEqual(by["B16e_balance_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B16f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B17_coherent_field"]["verdict"], "pass")
        self.assertEqual(by["B17a_net_is_plus"]["verdict"], "pass")
        self.assertEqual(by["B17b_cubic_not_live"]["verdict"], "fail")
        self.assertEqual(by["B17c_tube_still_cancels"]["verdict"], "fail")
        self.assertEqual(by["B17d_blob_is_not_bkm"]["verdict"], "fail")
        self.assertEqual(by["B17e_coherent_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B17f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B18_field_clock"]["verdict"], "pass")
        self.assertEqual(by["B18a_paths_stay_conc"]["verdict"], "pass")
        self.assertEqual(by["B18b_clock_did_not_save"]["verdict"], "fail")
        self.assertEqual(by["B18c_conc_not_short"]["verdict"], "fail")
        self.assertEqual(by["B18d_cubic_not_live_time"]["verdict"], "fail")
        self.assertEqual(by["B18e_field_occ_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B18f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B19_field_rates"]["verdict"], "pass")
        self.assertEqual(by["B19a_sign_mismatch"]["verdict"], "fail")
        self.assertEqual(by["B19b_not_the_blowup"]["verdict"], "fail")
        self.assertEqual(by["B19c_alpha_not_the_cubic"]["verdict"], "fail")
        self.assertEqual(by["B19d_gamma_not_visc"]["verdict"], "fail")
        self.assertEqual(by["B19e_field_glue_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B19f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B20_field_c"]["verdict"], "pass")
        self.assertEqual(by["B20a_blob_t0_not_saving"]["verdict"], "fail")
        self.assertEqual(by["B20b_paths_not_saving"]["verdict"], "fail")
        self.assertEqual(by["B20c_blob_visc_not_ladder"]["verdict"], "fail")
        self.assertEqual(by["B20d_offset_not_climb"]["verdict"], "fail")
        self.assertEqual(by["B20e_ns_climb_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B20f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B21_window_rates"]["verdict"], "pass")
        self.assertEqual(by["B21a_not_the_room"]["verdict"], "fail")
        self.assertEqual(by["B21b_not_the_sitting"]["verdict"], "fail")
        self.assertEqual(by["B21c_delta_j_not_prescribed"]["verdict"], "fail")
        self.assertEqual(by["B21d_sketch_did_not_save"]["verdict"], "fail")
        self.assertEqual(by["B21e_sketch_not_X_a_priori"]["verdict"], "open")
        self.assertEqual(by["B21f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B22_longer_readable"]["verdict"], "pass")
        self.assertEqual(by["B22a_longer_not_saving"]["verdict"], "fail")
        self.assertEqual(by["B22b_longer_not_ladder"]["verdict"], "fail")
        self.assertEqual(by["B22c_longer_no_high_fill"]["verdict"], "fail")
        self.assertEqual(by["B22d_longer_clock_did_not_save"]["verdict"], "fail")
        self.assertEqual(by["B22e_finer_open"]["verdict"], "open")
        self.assertEqual(by["B22f_not_a_pde_retune"]["verdict"], "fail")
        self.assertEqual(by["B_regularity"]["verdict"], "open")
        self.assertIn("B13f", payload["next_da_move"])
        self.assertLess(by["B1_t2_low_flux"]["rel_residual"], 1e-10)

    def test_no_regularity_pass_in_the_list(self):
        tmp = Path(tempfile.mkdtemp()) / "track_b_test.json"
        payload = run(out=tmp)
        for row in payload["lemmas"]:
            if "regular" in row["name"] or row["name"] == "B_regularity":
                self.assertNotEqual(row["verdict"], "pass", row["name"])


if __name__ == "__main__":
    unittest.main()
