"""Index of a rank-k lattice in its saturation, and relative index.

Two computations, both exact and independent of the HNF log:

1. saturation_index(B) = gcd of the k×k minors of the n×k
   generator matrix B (columns generate the lattice). This is 1
   iff the lattice is saturated in Z^n ∩ span_Q(B).

2. relative_index(B_sub, B_sat) = saturation_index(B_sub) /
   saturation_index(B_sat) when they span the same Q-space
   (otherwise refused). For a saturated ambient this equals
   |det A| where B_sub = B_sat A.
"""

from __future__ import annotations

from itertools import combinations
from math import gcd
from typing import List, Optional, Sequence, Tuple

from min_cycle_verifier_v2.exceptions import MalformedInputError
from min_cycle_verifier_v2.hnf import det
from min_cycle_verifier_v2.validate import (
    require_integer_matrix,
    require_integer_vector,
    shape,
)

Matrix = List[List[int]]
Vector = List[int]


def _gcd_list(vals: Sequence[int]) -> int:
    g = 0
    for v in vals:
        g = gcd(g, abs(v))
    return g


def _submatrix(A: Sequence[Sequence[int]], rows: Sequence[int], cols: Sequence[int]) -> Matrix:
    return [[A[i][j] for j in cols] for i in rows]


def minors_k(B: Sequence[Sequence[int]], k: int) -> List[int]:
    """All k×k minors of B (B is n×p, typically p=k)."""
    n, p = shape(B)
    if k < 0 or k > min(n, p):
        raise MalformedInputError(f"minor size k={k} invalid for {n}x{p}")
    if k == 0:
        return [1]
    out: List[int] = []
    for rows in combinations(range(n), k):
        for cols in combinations(range(p), k):
            out.append(det(_submatrix(B, rows, cols)))
    return out


def saturation_index(generators: Sequence[Sequence[int]]) -> int:
    """Index of the lattice generated by the given *columns* in its saturation.

    ``generators`` is a list of equal-length integer vectors (the
    columns). Rank is inferred as the size of a maximal independent
    set over Q, detected by a nonzero minor of that size. If the
    listed generators are Z-dependent extra copies, the gcd of
    maximal-rank minors of the possibly-fat matrix still equals the
    index of the lattice they generate.
    """
    if not generators:
        return 1
    # n x k matrix with columns = generators.
    k = len(generators)
    n = len(generators[0])
    B = [[generators[j][i] for j in range(k)] for i in range(n)]
    _, n2, k2 = require_integer_matrix(B)
    assert n2 == n and k2 == k
    # Rank = largest r with a nonzero r-minor.
    rank = 0
    for r in range(min(n, k), 0, -1):
        ms = minors_k(B, r)
        if any(m != 0 for m in ms):
            rank = r
            break
    if rank == 0:
        return 1  # {0} is saturated in {0}
    return _gcd_list(minors_k(B, rank)) or 1


def columns_as_matrix(generators: Sequence[Sequence[int]]) -> Matrix:
    if not generators:
        return []
    k = len(generators)
    n = len(generators[0])
    return [[generators[j][i] for j in range(k)] for i in range(n)]


def lattice_contains(generators: Sequence[Sequence[int]], v: Sequence[int]) -> Tuple[bool, Optional[Vector]]:
    """Does v lie in the Z-span of the generator columns?

    Returns (ok, coeffs) with generators * coeffs = v when ok.
    """
    if not generators:
        x = require_integer_vector(v, name="v")
        return (all(t == 0 for t in x), [] if all(t == 0 for t in x) else None)
    k = len(generators)
    n = len(generators[0])
    v_int = require_integer_vector(v, n=n, name="v")
    B = columns_as_matrix(generators)
    require_integer_matrix(B)

    # Rank via minors.
    rank = 0
    for r in range(min(n, k), 0, -1):
        if any(m != 0 for m in minors_k(B, r)):
            rank = r
            break
    if rank == 0:
        return (all(t == 0 for t in v_int), [0] * k if all(t == 0 for t in v_int) else None)

    # Unique Q-solution on a full-rank subset of columns, if k==rank.
    # If extra generators, try combinations of rank columns.
    col_sets = list(combinations(range(k), rank))
    row_sets = list(combinations(range(n), rank))
    for cols in col_sets:
        for rows in row_sets:
            sub = _submatrix(B, rows, cols)
            d = det(sub)
            if d == 0:
                continue
            rhs = [v_int[i] for i in rows]
            # Solve sub x = rhs via Cramer / adjugate: x = adj(sub) rhs / d
            coeffs_sub = _solve_square(sub, rhs)
            if coeffs_sub is None:
                continue
            x = [0] * k
            for a, c in zip(cols, coeffs_sub):
                x[a] = c
            if _matvec(B, x) == v_int:
                return True, x
            # This chart did not reconstruct v: v not in Q-span of these
            # columns, or rounding — try next.
    return False, None


def _matvec(B: Sequence[Sequence[int]], x: Sequence[int]) -> Vector:
    n = len(B)
    k = len(B[0]) if n else 0
    out = [0] * n
    for i in range(n):
        s = 0
        for j in range(k):
            s += B[i][j] * x[j]
        out[i] = s
    return out


def _solve_square(A: Sequence[Sequence[int]], b: Sequence[int]) -> Optional[Vector]:
    """Solve A x = b over Z, A square. None if no integer solution."""
    n = len(A)
    d = det(A)
    if d == 0:
        return None
    x: Vector = []
    for j in range(n):
        C = [_copy_row for _copy_row in (list(row) for row in A)]
        for i in range(n):
            C[i][j] = b[i]
        dj = det(C)
        if dj % d != 0:
            return None
        x.append(dj // d)
    if _matvec(A, x) != list(b):
        return None
    return x


def relative_index(
    generators_sub: Sequence[Sequence[int]],
    generators_sat: Sequence[Sequence[int]],
) -> int:
    """Index of L_sub inside L_sat, requiring equal Q-span and L_sub ⊆ L_sat."""
    if not generators_sat:
        if not generators_sub or all(all(x == 0 for x in g) for g in generators_sub):
            return 1
        raise MalformedInputError("sublattice is not inside the zero lattice")
    idx_sub = saturation_index(generators_sub)
    idx_sat = saturation_index(generators_sat)
    if idx_sat == 0 or idx_sub % idx_sat != 0:
        raise MalformedInputError(
            f"indices {idx_sub} and {idx_sat} are incompatible for a relative index"
        )
    # Confirm each sub generator lies in the sat lattice.
    for g in generators_sub:
        ok, _ = lattice_contains(generators_sat, g)
        if not ok:
            raise MalformedInputError("generator of sublattice is not in the saturated lattice")
    rel = idx_sub // idx_sat
    return rel
